apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo_python
  tags:
    - java
    - python
    - demo
  description: demo repo created for exp
  annotations:
    github.com/project-slug: abhkaush3/demo_python_repo
    backstage.io/managed-by-location: url:http://github.com/backstage/backstage/blob/master/catalog-info.yaml
    backstage.io/techdocs-ref: value
spec:
  type: java
  lifecycle: experimental
  owner: backstage
